### PR TITLE
Fix behaviour of leaking child threads when nesting

### LINKED ISSUE #102: forkThread children appear not to be cancelling if Async asks for it
Still trying to pin this down, but:

```haskell

    raceThreads_
        ( do
            t <- forkThread $ do 
                liftIO $ do
                    get "http://localhost:41112/" debugHandler
                write "Done"
            waitThread t
        )
        ( do
            sleepThread 3.0
            info "Racing"
        )
    info "Finishing..."
    sleepThread 10.0
    info "Done"
```

results in the HTTP request _not_ being cancelled when the second branch of the `raceThreads_` finishes.

### PR DESCRIPTION
**Pull request by istathar**
Closes #102.

Credit to @carlosdagos for recognizing that the problem was that the `Async.wait` was being cancelled, but that this AsyncCancelled was not being propagated to the child thread. Fixed by having `waitThreads` catch this exception and cancel the thread being waited on in turn. 

Clarify the documentation of behaviour of `forkThread` and `waitThread` in regard to what happens when exceptions are thrown.

### CODE REVIEW

File: core-program/lib/Core/Program/Threads.hs [hunk 1]
```diff
@@ -139,12 +145,28 @@ forkThread program = do
...
 
 @since 0.2.7
 -}
 waitThread :: Thread α -> Program τ α
-waitThread (Thread a) = liftIO $ Async.wait a
+waitThread (Thread a) = liftIO $ do
+    Safe.catchAsync
+        (Async.wait a)
+        ( \(e :: AsyncCancelled) -> do
+            cancel a
```
Comment (carlosdagos) [inline core-program/lib/Core/Program/Threads.hs:167]: Do you think it would be appropriate to have a debug log here?

**Review by carlosdagos — APPROVED** [review]
Thanks @istathar, small comment from me but otherwise looks good and the doc is clear

File: core-program/lib/Core/Program/Threads.hs (hunk 1 above)
Comment (istathar) [reply core-program/lib/Core/Program/Threads.hs:167]: Hm. I suspect no.

I thought about it, but I think the use case of having a to clean up child threads when one branch of a `race` succeeds it pretty common—and expected. Don't think we need to make noise that we have terminated child threads.

Something to keep thinking about, though.

**Comment by istathar** [comment]
Since @carlosdagos reviewed this I have added new functions `waitThread'` (return an Either), `waitThreads'` (do that for many threads), and `cancelThread` with the safety behaviour matching the improved `waitThread` which was the original subject of this branch.
